version: '3.8'

services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1

  app:
    container_name: easycode-app
    build: ./project
    restart: unless-stopped
    volumes:
      - ./project/:/var/www/local.easycode.com
    depends_on:
      - database

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./project/:/var/www/local.easycode.com
    depends_on:
      - app